services:
  mongodb:
    restart: always
    image: mongo:4.1.1
    container_name: "mongodb"
  request-processing:
    restart: always
    image: openjdk:17-alpine
    volumes:
      - ./target:/app
    working_dir: /app
    command: java -jar request-processing-0.0.1-SNAPSHOT.jar
    ports:
      - "8080:8080"
    depends_on:
      - mongodb